### ISSUE TITLE
Monalika Padma Reddy, Monalika-P

### ISSUE THREAD

**Issue by Monalika-P** [odu-cs625-datavis/public-fall23-mcw#17]
My name is Monalika Padma Reddy. The GitHUb User Name is Monalika-P

**Comment by weiglemc** [comment]
@Monalika-P Repo created, https://github.com/odu-cs625-datavis/fall23-mcw-Monalika-P

**Comment by weiglemc** [comment]
@Monalika-P - You aren't in my section. Please create an Issue in Dr. Veerasamy's public repo, https://github.com/odu-cs625-datavis/public-fall23-aveerasa

Let me know when you've copied your files over to the appropriate repo so that I can delete this one.
