### ISSUE TITLE
Manoj KUMAR MOOLA - manoj1808

### ISSUE THREAD

**Issue by manoj1808** [odu-cs625-datavis/public-fall23-mcw#19]

**Comment by weiglemc** [comment]
@manoj1808 Repo created, https://github.com/odu-cs625-datavis/fall23-mcw-manoj1808

**Comment by weiglemc** [comment]
@manoj1808 I'll be deleting the repo https://github.com/odu-cs625-datavis/fall23-mcw-manoj1808
